<?php
/**
 * iHelp247 WP Intermission — uninstall cleanup.
 * © ULXI — UnLimited eXchange, Inc. · published under the iHelp247 brand · GPL-2.0-or-later
 * Deletes all plugin options and removes marker-guarded generated drop-ins.
 * The override folder and all Media Library uploads are intentionally left
 * alone: they are the site owner's content.
 */
defined( 'WP_UNINSTALL_PLUGIN' ) || exit;

foreach ( array( 'enabled', 'mode', 'content', 'full_html', 'status', 'countdown', 'dropin', 'cd_on', 'cd_end', 'dberror', 'designer', 'force', 'hide_credit' ) as $ih247_key ) {
	delete_option( 'ihelp247_wp_intermission_' . $ih247_key );
}

// Remove generated drop-ins, but only those that are ours (marker-guarded).
foreach ( array( WP_CONTENT_DIR . '/maintenance.php', WP_CONTENT_DIR . '/db-error.php' ) as $ih247_file ) {
	if ( file_exists( $ih247_file ) ) {
		$ih247_head = (string) file_get_contents( $ih247_file, false, null, 0, 512 );
		if ( false !== strpos( $ih247_head, 'Generated by iHelp247 WP Intermission' ) ) {
			@unlink( $ih247_file );
		}
	}
}
