<?php
/**
 * Plugin Name:       iHelp247 WP Intermission
 * Plugin URI:        https://github.com/iHelp247/wp-intermission
 * Description:       Maintenance and coming-soon pages for WordPress — easy by default, powerful when you need them. Designer mode with true-scale device preview; template and full-HTML modes for power users. Countdown with launch actions, 503/200 control, core-update and DB-failure coverage. No bloat, no paywall, collects nothing.
 * Version:           1.5.3
 * Requires at least: 6.0
 * Requires PHP:      7.4
 * Author:            iHelp247 — by ULXI
 * Author URI:        https://ihelp247.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       wp-intermission
 * Update URI:        https://github.com/iHelp247/wp-intermission
 *
 * iHelp247 is the open-source publishing brand of ULXI — UnLimited eXchange,
 * Inc., the owner of the iHelp247 brand and this software.
 * The "Update URI" header prevents wordpress.org from ever pushing an
 * unrelated same-slug plugin as an "update" to this GitHub-distributed one.
 *
 * Naming note: "WPIM" in internal prefixes = WP Intermission.
 */

defined( 'ABSPATH' ) || exit;

/* -------------------------------------------------------------------------
 * Configuration — every tunable in one place. Change here, nowhere else.
 * ---------------------------------------------------------------------- */

define( 'IH247_WPIM_VERSION', '1.5.3' );

/** Option names. */
define( 'IH247_WPIM_OPTION', 'ihelp247_wp_intermission_enabled' );          // bool: maintenance mode on/off
define( 'IH247_WPIM_OPT_MODE', 'ihelp247_wp_intermission_mode' );           // 'template' | 'full' | 'designer'
define( 'IH247_WPIM_OPT_CONTENT', 'ihelp247_wp_intermission_content' );     // string: editor HTML injected at {{CONTENT}} (template mode)
define( 'IH247_WPIM_OPT_FULL', 'ihelp247_wp_intermission_full_html' );      // string: complete HTML document (full mode)
define( 'IH247_WPIM_OPT_STATUS', 'ihelp247_wp_intermission_status' );       // '503' | '200'
define( 'IH247_WPIM_OPT_COUNTDOWN', 'ihelp247_wp_intermission_countdown' ); // string: 'YYYY-MM-DDTHH:MM' site-timezone target for {ihelp-wp-countdown}
define( 'IH247_WPIM_OPT_DROPIN', 'ihelp247_wp_intermission_dropin' );       // bool: also cover WP core-update windows via wp-content/maintenance.php
define( 'IH247_WPIM_OPT_CD_ON', 'ihelp247_wp_intermission_cd_on' );           // bool: countdown feature enabled (explicit — a cleared date does not imply "off")
define( 'IH247_WPIM_OPT_CD_END', 'ihelp247_wp_intermission_cd_end' );         // 'none' | 'hide' | 'golive' — what happens at zero
define( 'IH247_WPIM_OPT_DBERROR', 'ihelp247_wp_intermission_dberror' );     // bool: also cover database-connection failures via wp-content/db-error.php
define( 'IH247_WPIM_OPT_DESIGNER', 'ihelp247_wp_intermission_designer' );   // array: Designer-mode fields (see ih247_wpim_designer_defaults)
define( 'IH247_WPIM_OPT_FORCE', 'ihelp247_wp_intermission_force' );         // bool: overwrite foreign maintenance.php / db-error.php drop-ins on save
define( 'IH247_WPIM_OPT_HIDE_CREDIT', 'ihelp247_wp_intermission_hide_credit' ); // bool: hide the small iHelp247 link on the served page

/** Users with this capability bypass maintenance and see the live site. */
define( 'IH247_WPIM_CAPABILITY', 'edit_posts' );

/** Retry-After header value (seconds) sent with a 503 response. */
define( 'IH247_WPIM_RETRY_AFTER', 600 );

/** Countdown token accepted inside content, full HTML, or templates. */
define( 'IH247_WPIM_COUNTDOWN_TOKEN', '{ihelp-wp-countdown}' );

/** Marker that identifies a drop-in generated by this plugin (never overwrite foreign files unless Force overwrite is on). */
define( 'IH247_WPIM_DROPIN_MARKER', 'Generated by iHelp247 WP Intermission' );

/** Hosted user guide & self-help (also ships in the plugin's docs/ folder). */
define( 'IH247_WPIM_DOCS_URL', 'https://ihelp247.com/wp-intermission/' );

/** Support links (Support & branding row on the settings page). One Square
 *  checkout covers everything — any amount, with a one-time / monthly toggle
 *  at checkout. All links open in a new tab. */
define( 'IH247_WPIM_DONATE_URL', 'https://square.link/u/NSPL6UTY' );                // Square checkout — any amount, one-time or monthly
define( 'IH247_WPIM_SUPPORT_URL', 'https://ihelp247.com/support' );                 // help & contact
define( 'IH247_WPIM_PROJECTS_URL', 'https://ihelp247.com' );                        // more iHelp247 plugins & projects
define( 'IH247_WPIM_REVIEW_URL', 'https://github.com/iHelp247/wp-intermission' );   // where to leave a review / star

/**
 * Optional per-site override folder (developer feature). If
 * wp-content/wp-intermission/template.html exists, template mode uses it
 * instead of the bundled template, and {{ASSETS_URL}} points at that folder.
 * Most sites never need this — "Full custom HTML" mode does everything from
 * the admin screen with no filesystem access.
 */
define( 'IH247_WPIM_OVERRIDE_DIR', WP_CONTENT_DIR . '/wp-intermission' );

/* -------------------------------------------------------------------------
 * Template + content resolution
 * ---------------------------------------------------------------------- */

function ih247_wpim_template_path() {
	$override = IH247_WPIM_OVERRIDE_DIR . '/template.html';
	$path     = file_exists( $override ) ? $override : __DIR__ . '/templates/template.html';
	return apply_filters( 'ihelp247_wp_intermission_template_path', $path );
}

function ih247_wpim_assets_url() {
	$override = IH247_WPIM_OVERRIDE_DIR . '/template.html';
	if ( file_exists( $override ) ) {
		$url = content_url( 'wp-intermission' );
	} else {
		// Default: a dedicated folder inside uploads — survives plugin, theme,
		// and core updates, and resolves to the same relative path on every
		// site, so fleet-shared HTML using {{ASSETS_URL}} is portable.
		$uploads = wp_get_upload_dir();
		$url     = untrailingslashit( $uploads['baseurl'] ) . '/wp-intermission';
	}
	return apply_filters( 'ihelp247_wp_intermission_assets_url', $url );
}

/** Make sure the uploads asset folder exists so FTP/Media drops have a home. */
function ih247_wpim_ensure_asset_dir() {
	$uploads = wp_get_upload_dir();
	wp_mkdir_p( untrailingslashit( $uploads['basedir'] ) . '/wp-intermission' );
}

/** Default editor content — generic and token-driven; brands itself to any site. */
function ih247_wpim_default_content() {
	return "<h1>{{SITE_NAME}}</h1>\n"
		. "<div class=\"line\"></div>\n"
		. "<p>We are working on something new. Please check back soon.</p>";
}

function ih247_wpim_get_content() {
	$content = get_option( IH247_WPIM_OPT_CONTENT, '' );
	return '' === trim( (string) $content ) ? ih247_wpim_default_content() : $content;
}

function ih247_wpim_get_mode() {
	// Designer is the fresh-install default: easiest surface first, with
	// template and full-HTML modes there for power users who want them.
	$mode = get_option( IH247_WPIM_OPT_MODE, 'designer' );
	return in_array( $mode, array( 'full', 'template', 'designer' ), true ) ? $mode : 'designer';
}

function ih247_wpim_get_status() {
	return '200' === get_option( IH247_WPIM_OPT_STATUS, '503' ) ? 200 : 503;
}

/* -------------------------------------------------------------------------
 * Designer mode — isolated, non-technical fields rendered into the styled
 * layout. No code required; live preview on the settings page.
 * ---------------------------------------------------------------------- */

function ih247_wpim_designer_defaults() {
	return array(
		'bg_url'         => '',
		'logo_url'       => '',
		'title'          => '{{SITE_NAME}}',
		'title_size'     => 28,
		'title_color'    => '#ffffff',
		'subtitle'       => '',
		'subtitle_size'  => 18,
		'subtitle_color' => '#d0d8e0',
		'text'           => 'We are working on something new. Please check back soon.',
		'text_size'      => 16,
		'text_color'     => '#bfc9d4',
		'disclaimer'     => '',
		'bg_style'       => 'default', // 'default' (stock dark gradient) | 'solid' | 'gradient'
		'bg_color'       => '#000510', // solid color / gradient outer-bottom color
		'bg_color2'      => '#0a2540', // gradient inner-top color
		'bg_dir'         => 'radial',  // 'radial' | 'vertical' | 'diagonal'
		'bg_overlay'     => '1',       // dark overlay + glass layers ('' = off, for light designs)
		'bg_glass_op'    => 50,        // glass strength 10–100 (%) — scales the overlay's darkness
		'cd_color'       => '#ffffff', // countdown digit color (labels/borders derived)
		'cd_shape'       => 'square',  // 'square' | 'rounded' | 'circle'
		// Countdown + footer font slots ('inherit' = use the body font).
		'cd_source'      => 'inherit',
		'cd_stack'       => 'mono',
		'cd_google'      => '',
		'cd_family'      => '',
		'cd_url'         => '',
		'footer_source'  => 'inherit',
		'footer_stack'   => 'system-ui',
		'footer_google'  => '',
		'footer_family'  => '',
		'footer_url'     => '',
		// Two font slots: heading (title) and body (everything else).
		// Each: source 'system' | 'google' | 'custom'.
		'heading_source' => 'system',
		'heading_stack'  => 'system-ui',
		'heading_google' => '',
		'heading_family' => '',
		'heading_url'    => '',
		'body_source'    => 'system',
		'body_stack'     => 'system-ui',
		'body_google'    => '',
		'body_family'    => '',
		'body_url'       => '',
	);
}

/** Curated web-safe system stacks — native rendering, zero downloads. */
function ih247_wpim_system_stacks() {
	return array(
		'system-ui' => array( 'label' => 'System UI — Segoe UI on Windows, San Francisco on Mac (the classic stack)', 'css' => "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" ),
		'arial'     => array( 'label' => 'Arial / Helvetica', 'css' => "Arial, 'Helvetica Neue', Helvetica, sans-serif" ),
		'verdana'   => array( 'label' => 'Verdana / Tahoma', 'css' => 'Verdana, Geneva, Tahoma, sans-serif' ),
		'trebuchet' => array( 'label' => 'Trebuchet MS', 'css' => "'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', sans-serif" ),
		'georgia'   => array( 'label' => 'Georgia (serif)', 'css' => "Georgia, 'Times New Roman', Times, serif" ),
		'palatino'  => array( 'label' => 'Palatino / Book Antiqua (serif)', 'css' => "'Palatino Linotype', Palatino, 'Book Antiqua', Georgia, serif" ),
		'didone'    => array( 'label' => 'Didot / Bodoni (display serif)', 'css' => "Didot, 'Bodoni MT', 'Playfair Display', Georgia, serif" ),
		'mono'      => array( 'label' => 'Monospace — Consolas / Menlo', 'css' => "'Cascadia Code', Consolas, Menlo, Monaco, 'Courier New', monospace" ),
	);
}

function ih247_wpim_designer() {
	$d = get_option( IH247_WPIM_OPT_DESIGNER, array() );
	$d = is_array( $d ) ? $d : array();
	return wp_parse_args( $d, ih247_wpim_designer_defaults() );
}

function ih247_wpim_sanitize_designer( $in ) {
	$out = ih247_wpim_designer_defaults();
	$in  = is_array( $in ) ? $in : array();

	foreach ( array( 'bg_url', 'logo_url' ) as $k ) {
		if ( isset( $in[ $k ] ) ) {
			$out[ $k ] = esc_url_raw( trim( (string) $in[ $k ] ) );
		}
	}
	$inline = array( 'strong' => array(), 'em' => array(), 'b' => array(), 'i' => array(), 'u' => array(), 'br' => array(), 'a' => array( 'href' => true, 'target' => true ) );
	foreach ( array( 'title', 'subtitle' ) as $k ) {
		if ( isset( $in[ $k ] ) ) {
			$out[ $k ] = wp_kses( (string) $in[ $k ], $inline );
		}
	}
	$stacks = ih247_wpim_system_stacks();
	foreach ( array( 'heading', 'body', 'cd', 'footer' ) as $slot ) {
		if ( isset( $in[ $slot . '_source' ] ) && in_array( $in[ $slot . '_source' ], array( 'system', 'google', 'custom', 'inherit' ), true ) ) {
			$out[ $slot . '_source' ] = $in[ $slot . '_source' ];
		}
		if ( isset( $in[ $slot . '_stack' ] ) && isset( $stacks[ $in[ $slot . '_stack' ] ] ) ) {
			$out[ $slot . '_stack' ] = $in[ $slot . '_stack' ];
		}
		foreach ( array( '_google', '_family' ) as $suffix ) {
			if ( isset( $in[ $slot . $suffix ] ) ) {
				$out[ $slot . $suffix ] = sanitize_text_field( (string) $in[ $slot . $suffix ] );
			}
		}
		if ( isset( $in[ $slot . '_url' ] ) ) {
			$out[ $slot . '_url' ] = esc_url_raw( trim( (string) $in[ $slot . '_url' ] ) );
		}
	}
	foreach ( array( 'text', 'disclaimer' ) as $k ) {
		if ( isset( $in[ $k ] ) ) {
			$out[ $k ] = wp_kses_post( (string) $in[ $k ] );
		}
	}
	foreach ( array( 'title_size', 'subtitle_size', 'text_size' ) as $k ) {
		if ( isset( $in[ $k ] ) ) {
			$out[ $k ] = max( 8, min( 160, absint( $in[ $k ] ) ) );
		}
	}
	foreach ( array( 'title_color', 'subtitle_color', 'text_color', 'cd_color', 'bg_color', 'bg_color2' ) as $k ) {
		if ( isset( $in[ $k ] ) ) {
			$hex = sanitize_hex_color( (string) $in[ $k ] );
			if ( $hex ) {
				$out[ $k ] = $hex;
			}
		}
	}
	if ( isset( $in['bg_style'] ) && in_array( $in['bg_style'], array( 'default', 'solid', 'gradient' ), true ) ) {
		$out['bg_style'] = $in['bg_style'];
	}
	if ( isset( $in['bg_dir'] ) && in_array( $in['bg_dir'], array( 'radial', 'vertical', 'diagonal' ), true ) ) {
		$out['bg_dir'] = $in['bg_dir'];
	}
	$out['bg_overlay'] = ! empty( $in['bg_overlay'] ) ? '1' : '';
	if ( isset( $in['bg_glass_op'] ) ) {
		$out['bg_glass_op'] = max( 10, min( 100, absint( $in['bg_glass_op'] ) ) );
	}
	if ( isset( $in['cd_shape'] ) && in_array( $in['cd_shape'], array( 'square', 'rounded', 'circle' ), true ) ) {
		$out['cd_shape'] = $in['cd_shape'];
	}
	return $out;
}

/** hex (#rrggbb) → rgba() string. */
function ih247_wpim_hex_rgba( $hex, $alpha ) {
	$hex = ltrim( (string) $hex, '#' );
	if ( 3 === strlen( $hex ) ) {
		$hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
	}
	if ( 6 !== strlen( $hex ) ) {
		$hex = 'ffffff';
	}
	return 'rgba(' . hexdec( substr( $hex, 0, 2 ) ) . ',' . hexdec( substr( $hex, 2, 2 ) ) . ',' . hexdec( substr( $hex, 4, 2 ) ) . ',' . $alpha . ')';
}

/** Resolve one font slot to a CSS stack; appends any needed link/@font-face markup. */
function ih247_wpim_resolve_slot_font( $d, $slot, &$links, &$faces ) {
	$stacks = ih247_wpim_system_stacks();
	$stack  = $stacks['system-ui']['css'];
	$src    = isset( $d[ $slot . '_source' ] ) ? $d[ $slot . '_source' ] : 'system';

	if ( 'inherit' === $src ) {
		// Follow the body font (guard: body itself never inherits).
		return 'body' === $slot ? $stack : ih247_wpim_resolve_slot_font( $d, 'body', $links, $faces );
	}

	if ( 'system' === $src && isset( $stacks[ $d[ $slot . '_stack' ] ] ) ) {
		$stack = $stacks[ $d[ $slot . '_stack' ] ]['css'];
	} elseif ( 'google' === $src && '' !== trim( $d[ $slot . '_google' ] ) ) {
		$fam = trim( $d[ $slot . '_google' ] );
		if ( false === strpos( $links, 'fonts.googleapis.com">' ) ) {
			$links .= '<link rel="preconnect" href="https://fonts.googleapis.com">'
				. '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
		}
		// No weight axis on purpose: css2 hard-errors if ANY requested weight
		// is missing from the family. Spaces must be '+', hence urlencode.
		$css2 = 'https://fonts.googleapis.com/css2?family=' . urlencode( $fam ) . '&display=swap';
		if ( false === strpos( $links, $css2 ) ) {
			$links .= '<link href="' . $css2 . '" rel="stylesheet">';
		}
		$stack = "'" . esc_attr( $fam ) . "', " . $stack;
	} elseif ( 'custom' === $src && $d[ $slot . '_url' ] && $d[ $slot . '_family' ] ) {
		$face = "@font-face{font-family:'" . esc_attr( $d[ $slot . '_family' ] ) . "';src:url('" . esc_url( $d[ $slot . '_url' ] ) . "') format('woff2');font-display:swap;}";
		if ( false === strpos( $faces, $face ) ) {
			$faces .= $face;
		}
		$stack = "'" . esc_attr( $d[ $slot . '_family' ] ) . "', " . $stack;
	}
	return $stack;
}

/** Render the Designer fields into a complete HTML document. */
function ih247_wpim_designer_html( $d, $cd_ts = null, $cd_end = null ) {
	$font_face  = '';
	$head_links = '';

	// Resolve each font slot (heading = title; body = everything else).
	$heading_stack = ih247_wpim_resolve_slot_font( $d, 'heading', $head_links, $font_face );
	$font_stack    = ih247_wpim_resolve_slot_font( $d, 'body', $head_links, $font_face );
	$footer_stack  = ih247_wpim_resolve_slot_font( $d, 'footer', $head_links, $font_face );

	// Background: style base (stock gradient / solid / custom gradient), image
	// layered over it when set, overlay+glass controlled by their own toggle.
	$c1 = esc_attr( $d['bg_color'] ? $d['bg_color'] : '#000510' );
	$c2 = esc_attr( $d['bg_color2'] ? $d['bg_color2'] : '#0a2540' );
	if ( 'solid' === $d['bg_style'] ) {
		$base_layer = 'linear-gradient(' . $c1 . ',' . $c1 . ')'; // gradient-wrapped so it can stack under an image
	} elseif ( 'gradient' === $d['bg_style'] ) {
		if ( 'vertical' === $d['bg_dir'] ) {
			$base_layer = 'linear-gradient(180deg, ' . $c2 . ' 0%, ' . $c1 . ' 100%)';
		} elseif ( 'diagonal' === $d['bg_dir'] ) {
			$base_layer = 'linear-gradient(135deg, ' . $c2 . ' 0%, ' . $c1 . ' 100%)';
		} else {
			$base_layer = 'radial-gradient(circle at 50% 35%, ' . $c2 . ' 0%, ' . $c1 . ' 70%)';
		}
	} else {
		$base_layer = 'radial-gradient(circle at 50% 35%, #0a2540 0%, #000510 70%)';
	}
	$bg_layer = $d['bg_url']
		? "url('" . esc_url( $d['bg_url'] ) . "') no-repeat center center/cover, " . $base_layer
		: $base_layer;
	$body_bg  = 'default' === $d['bg_style'] ? '#000510' : $c1;
	$flat_bg  = '' === $d['bg_overlay']; // overlay+glass off

	$logo = $d['logo_url']
		? '<img src="' . esc_url( $d['logo_url'] ) . '" alt="" class="logo" onerror="this.style.display=\'none\'">'
		: '';

	$subtitle = '' !== trim( $d['subtitle'] )
		? '<p class="sub" style="font-size:' . (int) $d['subtitle_size'] . 'px;color:' . esc_attr( $d['subtitle_color'] ) . ';">' . $d['subtitle'] . '</p>'
		: '';

	$countdown = ih247_wpim_countdown_html( $d, $cd_ts, $cd_end ); // pass through so unsaved preview edits render

	$disclaimer = '' !== trim( $d['disclaimer'] )
		? '<div class="disclaimer">' . nl2br( $d['disclaimer'] ) . '</div>'
		: '';

	return '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex">
<title>{{SITE_NAME}}</title>
' . $head_links . '
<style>
' . $font_face . '
* { margin: 0; padding: 0; box-sizing: border-box; }
body { height: 100vh; font-family: ' . $font_stack . '; color: #fff; overflow: hidden; background: ' . $body_bg . '; }
.bg { position: fixed; width: 100%; height: 100%; background: ' . $bg_layer . '; z-index: -3; animation: slowZoom 30s ease-in-out infinite alternate; }
@keyframes slowZoom { from { transform: scale(1); } to { transform: scale(1.05); } }
.overlay { position: fixed; width: 100%; height: 100%; background: radial-gradient(circle at center, rgba(0,20,40,0.4), rgba(0,5,15,0.9)), linear-gradient(to bottom, rgba(0,0,0,0.4), rgba(0,0,0,0.85)); z-index: -2; }
.glass { position: fixed; width: 100%; height: 100%; backdrop-filter: blur(2px); z-index: -1; }
.container { height: 100%; display: flex; justify-content: center; align-items: center; text-align: center; flex-direction: column; padding: 20px; animation: fadeIn 1.2s ease; }
.logo { width: 320px; max-width: 80%; margin-bottom: 40px; filter: drop-shadow(0 0 30px rgba(255,255,255,0.15)) drop-shadow(0 0 60px rgba(0,150,255,0.1)); }
h1 { font-family: ' . $heading_stack . '; font-weight: 500; letter-spacing: 1.2px; margin-bottom: 14px; }
.line { width: 70px; height: 2px; margin: 18px auto; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.6), transparent); }
.container p { max-width: 560px; line-height: 1.5; }
.sub { margin-bottom: 6px; }
.footer { position: absolute; bottom: 25px; left: 0; right: 0; text-align: center; font-size: 12px; color: rgba(255,255,255,0.5); letter-spacing: 0.5px; font-family: ' . $footer_stack . '; }
.disclaimer { max-width: 640px; margin: 8px auto 0; font-size: 11px; line-height: 1.5; color: rgba(255,255,255,0.35); }
@keyframes fadeIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }
</style>
</head>
<body>
<div class="bg"></div>
' . ( $flat_bg ? '' : '<div class="overlay" style="opacity:' . ( max( 10, min( 100, (int) $d['bg_glass_op'] ) ) / 100 ) . ';"></div>
<div class="glass"></div>' ) . '
<div class="container">
' . $logo . '
<h1 style="font-size:' . (int) $d['title_size'] . 'px;color:' . esc_attr( $d['title_color'] ) . ';">' . $d['title'] . '</h1>
<div class="line"></div>
' . $subtitle . $countdown . '
<p style="font-size:' . (int) $d['text_size'] . 'px;color:' . esc_attr( $d['text_color'] ) . ';margin-top:18px;">' . nl2br( $d['text'] ) . '</p>
</div>
<div class="footer">
&copy; {{YEAR}} {{SITE_NAME}}
' . $disclaimer . '
</div>
</body>
</html>';
}

/** Allow self-hosted font uploads through the Media Library (admins only). */
function ih247_wpim_font_mimes( $mimes ) {
	if ( current_user_can( 'manage_options' ) ) {
		$mimes['woff']  = 'font/woff';
		$mimes['woff2'] = 'font/woff2';
	}
	return $mimes;
}
add_filter( 'upload_mimes', 'ih247_wpim_font_mimes' );

/** Live preview endpoint for the settings page (unsaved field values). */
function ih247_wpim_designer_preview_ajax() {
	check_ajax_referer( 'ih247_wpim_preview', 'nonce' );
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( '', '', 403 );
	}
	$d = ih247_wpim_sanitize_designer( wp_unslash( isset( $_POST['d'] ) ? (array) $_POST['d'] : array() ) );

	// Unsaved countdown state comes along too, so date/enable/end changes preview live.
	$cd_on  = ! empty( $_POST['cd_on'] );
	$cd_ts  = $cd_on ? ih247_wpim_parse_cd( sanitize_text_field( wp_unslash( isset( $_POST['cd_target'] ) ? $_POST['cd_target'] : '' ) ) ) : 0;
	$cd_end = isset( $_POST['cd_end'] ) && in_array( $_POST['cd_end'], array( 'none', 'hide', 'golive' ), true ) ? $_POST['cd_end'] : 'none';

	header( 'Content-Type: text/html; charset=utf-8' );
	echo ih247_wpim_apply_tokens( ih247_wpim_designer_html( $d, $cd_ts, $cd_end ) ); // phpcs:ignore WordPress.Security.EscapeOutput
	wp_die();
}
add_action( 'wp_ajax_ih247_wpim_designer_preview', 'ih247_wpim_designer_preview_ajax' );

/* -------------------------------------------------------------------------
 * Countdown — {ihelp-wp-countdown} token
 * ---------------------------------------------------------------------- */

/** Parse a 'YYYY-MM-DDTHH:MM' string in the site timezone → timestamp, or 0. */
function ih247_wpim_parse_cd( $raw ) {
	$raw = trim( (string) $raw );
	if ( '' === $raw ) {
		return 0;
	}
	try {
		$dt = new DateTimeImmutable( $raw, wp_timezone() );
		return $dt->getTimestamp();
	} catch ( Exception $e ) {
		return 0;
	}
}

/** Is the countdown feature enabled? */
function ih247_wpim_cd_enabled() {
	return (bool) get_option( IH247_WPIM_OPT_CD_ON, false );
}

/** What happens at zero: 'none' | 'hide' | 'golive'. */
function ih247_wpim_cd_end() {
	$v = get_option( IH247_WPIM_OPT_CD_END, 'none' );
	return in_array( $v, array( 'none', 'hide', 'golive' ), true ) ? $v : 'none';
}

/** Target timestamp (site timezone) — 0 when the feature is off, unset, or invalid. */
function ih247_wpim_countdown_ts() {
	if ( ! ih247_wpim_cd_enabled() ) {
		return 0;
	}
	return ih247_wpim_parse_cd( get_option( IH247_WPIM_OPT_COUNTDOWN, '' ) );
}

/** Markup + CSS + JS replacing the countdown token. Empty string if no target set.
 *  $d / $ts / $end override saved values — the live preview passes unsaved
 *  fields through, so changes render without a save. */
function ih247_wpim_countdown_html( $d = null, $ts = null, $end = null ) {
	if ( null === $ts ) {
		$ts = ih247_wpim_countdown_ts();
	}
	if ( ! $ts ) {
		return '';
	}
	if ( null === $end ) {
		$end = ih247_wpim_cd_end();
	}
	$ms = $ts * 1000;

	$cells = '';
	foreach ( array( 'Days', 'Hours', 'Minutes', 'Seconds' ) as $label ) {
		$cells .= '<span class="ih-cd-cell"><b>--</b><i>' . $label . '</i></span>';
	}

	// Style options (set in Designer, honored in every mode the token runs in).
	if ( null === $d ) {
		$d = ih247_wpim_designer();
	}
	$links   = '';
	$faces   = '';
	$cd_font = ih247_wpim_resolve_slot_font( $d, 'cd', $links, $faces );
	$c      = $d['cd_color'] ? $d['cd_color'] : '#ffffff';
	$shape  = '';
	if ( 'rounded' === $d['cd_shape'] ) {
		$shape = '.ih-cd-cell{border-radius:12px;}';
	} elseif ( 'circle' === $d['cd_shape'] ) {
		$shape = '.ih-cd-cell{width:88px;height:88px;min-width:0;padding:0;border-radius:50%;justify-content:center;}'
			. '.ih-cd-cell b{font-size:24px;}'
			. '@media(max-width:480px){.ih-cd-cell{width:64px;height:64px;}.ih-cd-cell b{font-size:18px;}}';
	}

	return ( $links ? $links : '' )
		. '<div class="ih-cd" data-t="' . esc_attr( $ms ) . '" data-end="' . esc_attr( $end ) . '">' . $cells . '</div>'
		. '<style>'
		. ( $faces ? $faces : '' )
		. '.ih-cd{display:flex;gap:14px;justify-content:center;margin:26px auto 0;font-family:' . $cd_font . ';}'
		. '.ih-cd-cell{display:flex;flex-direction:column;align-items:center;min-width:74px;padding:14px 10px;'
		. 'border:1px solid ' . ih247_wpim_hex_rgba( $c, 0.35 ) . ';background:' . ih247_wpim_hex_rgba( $c, 0.07 ) . ';backdrop-filter:blur(6px);}'
		. '.ih-cd-cell b{font-size:28px;font-weight:600;letter-spacing:1px;font-variant-numeric:tabular-nums;color:' . esc_attr( $c ) . ';}'
		. '.ih-cd-cell i{font-style:normal;font-size:10px;letter-spacing:2px;text-transform:uppercase;'
		. 'color:' . ih247_wpim_hex_rgba( $c, 0.6 ) . ';margin-top:6px;}'
		. '@media(max-width:480px){.ih-cd{gap:8px}.ih-cd-cell{min-width:58px;padding:10px 6px}.ih-cd-cell b{font-size:20px}}'
		. $shape
		. '</style>'
		. '<script>(function(){if(window.ihCd)return;window.ihCd=1;'
		. 'var armed=false,fired=false;'
		. 'var tick=function(){var els=document.querySelectorAll(".ih-cd");'
		. 'for(var j=0;j<els.length;j++){var el=els[j],d=+el.getAttribute("data-t")-Date.now();'
		. 'if(d>0)armed=true;if(d<0)d=0;'
		. 'var s=Math.floor(d/1000),v=[Math.floor(s/86400),Math.floor((s%86400)/3600),Math.floor((s%3600)/60),s%60],'
		. 'b=el.querySelectorAll("b");for(var i=0;i<4;i++){b[i].textContent=("0"+v[i]).slice(-2);}'
		// At zero, honor the configured end behavior: 'hide' removes the counter;
		// 'golive' reloads once ~2s later (armed guard: pages that load with the
		// target already past never reload, so no refresh loops); 'none' shows 00s.
		. 'var e=el.getAttribute("data-end");'
		. 'if(0===d&&"hide"===e){el.style.display="none";}'
		. 'if(0===d&&"golive"===e&&armed&&!fired){fired=true;setTimeout(function(){location.reload();},2000);}}};'
		. 'tick();setInterval(tick,1000);})();</script>';
}

/* -------------------------------------------------------------------------
 * Page build — one function renders the final HTML for every consumer
 * (front-end response, preview, and the generated core-update drop-in).
 * ---------------------------------------------------------------------- */

/** Token substitution shared by both modes. */
function ih247_wpim_apply_tokens( $html ) {
	$cd   = ih247_wpim_countdown_html();
	$html = str_replace( IH247_WPIM_COUNTDOWN_TOKEN, $cd, $html );
	$html = str_replace(
		array( '{{ASSETS_URL}}', '{{SITE_NAME}}', '{{YEAR}}' ),
		array( esc_url( ih247_wpim_assets_url() ), esc_html( get_bloginfo( 'name' ) ), gmdate( 'Y' ) ),
		$html
	);
	return $html;
}

/** Small iHelp247 link, bottom-right of the served page. One checkbox on the
 *  settings page removes it — free either way, no strings attached. Injected
 *  just before </body> in every mode; documents without </body> are left alone. */
function ih247_wpim_inject_credit( $html ) {
	if ( get_option( IH247_WPIM_OPT_HIDE_CREDIT, false ) ) {
		return $html;
	}
	$credit = '<a href="' . esc_url( IH247_WPIM_PROJECTS_URL ) . '" target="_blank" rel="noopener nofollow"'
		. ' style="position:fixed;right:14px;bottom:10px;z-index:9;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;'
		. 'font-size:11px;letter-spacing:.4px;color:inherit;opacity:.35;text-decoration:none;">'
		. esc_html__( 'intermission by iHelp247', 'wp-intermission' ) . '</a>';
	$pos = strripos( $html, '</body>' );
	return false === $pos ? $html : substr_replace( $html, $credit . "\n", $pos, 0 );
}

function ih247_wpim_build_html() {
	$mode = ih247_wpim_get_mode();

	if ( 'designer' === $mode ) {
		return apply_filters( 'ihelp247_wp_intermission_html', ih247_wpim_inject_credit( ih247_wpim_apply_tokens( ih247_wpim_designer_html( ih247_wpim_designer() ) ) ) );
	}

	if ( 'full' === $mode ) {
		$html = (string) get_option( IH247_WPIM_OPT_FULL, '' );
		if ( '' !== trim( $html ) ) {
			return apply_filters( 'ihelp247_wp_intermission_html', ih247_wpim_inject_credit( ih247_wpim_apply_tokens( $html ) ) );
		}
		// Fall through to template mode if full HTML is empty — never serve a blank page.
	}

	$template = ih247_wpim_template_path();
	if ( ! is_readable( $template ) ) {
		return '';
	}
	$html = file_get_contents( $template );

	// Inject editor content. Custom templates without {{CONTENT}} still work as-is.
	if ( false !== strpos( $html, '{{CONTENT}}' ) ) {
		$html = str_replace( '{{CONTENT}}', ih247_wpim_get_content(), $html );
	}

	return apply_filters( 'ihelp247_wp_intermission_html', ih247_wpim_inject_credit( ih247_wpim_apply_tokens( $html ) ) );
}

/* -------------------------------------------------------------------------
 * Front-end: serve the maintenance page
 * ---------------------------------------------------------------------- */

function ih247_wpim_is_enabled() {
	return (bool) get_option( IH247_WPIM_OPTION, false );
}

function ih247_wpim_should_bypass() {
	$bypass = current_user_can( IH247_WPIM_CAPABILITY );
	if ( $bypass && isset( $_GET['ihelp247_wp_intermission_preview'] ) ) {
		$bypass = false; // Logged-in editors can force-preview.
	}
	return apply_filters( 'ihelp247_wp_intermission_bypass', $bypass );
}

function ih247_wpim_maybe_serve() {
	$preview = isset( $_GET['ihelp247_wp_intermission_preview'] ) && current_user_can( IH247_WPIM_CAPABILITY );

	// Countdown end behavior 'golive': server-side auto-disable. Otherwise the
	// countdown is display-only — reaching zero changes nothing.
	if ( ih247_wpim_is_enabled() && 'golive' === ih247_wpim_cd_end() ) {
		$ts = ih247_wpim_countdown_ts();
		if ( $ts && time() >= $ts ) {
			update_option( IH247_WPIM_OPTION, false ); // maintenance ends itself at T-0
		}
	}

	if ( ! ih247_wpim_is_enabled() && ! $preview ) {
		return;
	}
	if ( is_admin() || wp_doing_ajax() || wp_doing_cron() ) {
		return; // Never block wp-admin, AJAX, or cron. wp-login is untouched by design.
	}
	if ( ! $preview && ih247_wpim_should_bypass() ) {
		return;
	}

	$html = ih247_wpim_build_html();
	if ( '' === $html ) {
		return; // Fail open: a missing template must never white-screen the site.
	}

	$status = ih247_wpim_get_status();

	nocache_headers();
	status_header( $status );
	if ( 503 === $status ) {
		header( 'Retry-After: ' . absint( IH247_WPIM_RETRY_AFTER ) );
	}
	header( 'Content-Type: text/html; charset=utf-8' );
	echo $html; // phpcs:ignore WordPress.Security.EscapeOutput -- intentional raw template output.
	exit;
}
add_action( 'template_redirect', 'ih247_wpim_maybe_serve', 0 );

/* -------------------------------------------------------------------------
 * Core-update drop-in (wp-content/maintenance.php)
 *
 * While WordPress runs core/plugin/theme updates, plugins do not execute —
 * core serves wp-content/maintenance.php instead, if present. When the
 * checkbox is on, this plugin generates that file as a static snapshot of
 * the same page, and regenerates it on every settings save. Drop-ins are
 * outside the scope of core updates, so WP never overwrites it. The update
 * window is always genuinely temporary, so the drop-in always sends 503.
 * ---------------------------------------------------------------------- */

function ih247_wpim_dropin_path() {
	return WP_CONTENT_DIR . '/maintenance.php';
}

/** True when no drop-in exists, or the existing one is ours. */
function ih247_wpim_dropin_is_ours_or_absent() {
	$path = ih247_wpim_dropin_path();
	if ( ! file_exists( $path ) ) {
		return true;
	}
	$head = (string) file_get_contents( $path, false, null, 0, 512 );
	return false !== strpos( $head, IH247_WPIM_DROPIN_MARKER );
}

/** Foreign files are respected by default; the opt-in Force overwrite option
 *  replaces them on save. Unreliable by design: the file is only checked and
 *  replaced when settings are saved — it is not monitored, and the other tool
 *  can recreate its file at any time. */
function ih247_wpim_force_overwrite() {
	return (bool) get_option( IH247_WPIM_OPT_FORCE, false );
}

function ih247_wpim_write_dropin() {
	if ( ! ih247_wpim_dropin_is_ours_or_absent() && ! ih247_wpim_force_overwrite() ) {
		return false; // Never clobber a hand-made drop-in unless explicitly forced.
	}
	$html = ih247_wpim_build_html();
	if ( '' === $html ) {
		return false;
	}
	$php = "<?php\n"
		. '/* ' . IH247_WPIM_DROPIN_MARKER . ' v' . IH247_WPIM_VERSION . ' on ' . gmdate( 'c' ) . ".\n"
		. "   Do not edit — regenerated whenever the plugin's settings are saved. */\n"
		. "http_response_code( 503 ); // protocol-agnostic (HTTP/1.1 and HTTP/2 both correct)\n"
		. "header( 'Retry-After: " . absint( IH247_WPIM_RETRY_AFTER ) . "' );\n"
		. "header( 'Content-Type: text/html; charset=utf-8' );\n"
		. "?>" . $html;
	return false !== @file_put_contents( ih247_wpim_dropin_path(), $php );
}

function ih247_wpim_remove_dropin() {
	$path = ih247_wpim_dropin_path();
	if ( file_exists( $path ) && ih247_wpim_dropin_is_ours_or_absent() ) {
		@unlink( $path );
	}
}

/* ---- Database-failure drop-in (wp-content/db-error.php) -------------------
 * When WordPress cannot connect to the database, core serves
 * wp-content/db-error.php (if present) instead of the bare "Error
 * establishing a database connection" screen. Same generate/sync/marker
 * rules as the maintenance drop-in. It runs with NO WordPress loaded, so it
 * is a static snapshot; a timestamped HTML comment is appended so anyone
 * viewing source can tell a DB outage from planned maintenance. Leave the
 * checkbox OFF in environments where you want raw errors in your face. */

function ih247_wpim_dberror_path() {
	return WP_CONTENT_DIR . '/db-error.php';
}

function ih247_wpim_dberror_is_ours_or_absent() {
	$path = ih247_wpim_dberror_path();
	if ( ! file_exists( $path ) ) {
		return true;
	}
	$head = (string) file_get_contents( $path, false, null, 0, 512 );
	return false !== strpos( $head, IH247_WPIM_DROPIN_MARKER );
}

function ih247_wpim_write_dberror() {
	if ( ! ih247_wpim_dberror_is_ours_or_absent() && ! ih247_wpim_force_overwrite() ) {
		return false;
	}
	$html = ih247_wpim_build_html();
	if ( '' === $html ) {
		return false;
	}
	$html .= "\n<!-- iHelp247 WP Intermission: served by wp-content/db-error.php — the database was unreachable when this page was delivered. Snapshot generated " . gmdate( 'c' ) . '. -->';
	$php   = "<?php\n"
		. '/* ' . IH247_WPIM_DROPIN_MARKER . ' v' . IH247_WPIM_VERSION . ' on ' . gmdate( 'c' ) . " (db-error drop-in).\n"
		. "   Do not edit — regenerated whenever the plugin's settings are saved. */\n"
		. "http_response_code( 503 );\n"
		. "header( 'Retry-After: 300' );\n"
		. "header( 'Content-Type: text/html; charset=utf-8' );\n"
		. "?>" . $html;
	return false !== @file_put_contents( ih247_wpim_dberror_path(), $php );
}

function ih247_wpim_remove_dberror() {
	$path = ih247_wpim_dberror_path();
	if ( file_exists( $path ) && ih247_wpim_dberror_is_ours_or_absent() ) {
		@unlink( $path );
	}
}

function ih247_wpim_sync_dropin() {
	ih247_wpim_ensure_asset_dir();

	if ( get_option( IH247_WPIM_OPT_DROPIN, false ) ) {
		ih247_wpim_write_dropin();
	} else {
		ih247_wpim_remove_dropin();
	}

	if ( get_option( IH247_WPIM_OPT_DBERROR, false ) ) {
		ih247_wpim_write_dberror();
	} else {
		ih247_wpim_remove_dberror();
	}
}

/** Regenerate whenever any of our options change. */
function ih247_wpim_option_changed( $option ) {
	static $ours = null;
	if ( null === $ours ) {
		$ours = array(
			IH247_WPIM_OPTION,
			IH247_WPIM_OPT_MODE,
			IH247_WPIM_OPT_CONTENT,
			IH247_WPIM_OPT_FULL,
			IH247_WPIM_OPT_STATUS,
			IH247_WPIM_OPT_COUNTDOWN,
			IH247_WPIM_OPT_DROPIN,
			IH247_WPIM_OPT_CD_ON,
			IH247_WPIM_OPT_CD_END,
			IH247_WPIM_OPT_DBERROR,
			IH247_WPIM_OPT_FORCE,
			IH247_WPIM_OPT_HIDE_CREDIT,
		);
	}
	// Force overwrite implies core-update coverage (server-side backstop for
	// the settings-page JS): turning force on turns the drop-in on too.
	if ( IH247_WPIM_OPT_FORCE === $option && get_option( IH247_WPIM_OPT_FORCE, false ) && ! get_option( IH247_WPIM_OPT_DROPIN, false ) ) {
		update_option( IH247_WPIM_OPT_DROPIN, true );
	}

	if ( in_array( $option, $ours, true ) ) {
		ih247_wpim_sync_dropin();
	}
}
add_action( 'updated_option', 'ih247_wpim_option_changed' );
add_action( 'added_option', 'ih247_wpim_option_changed' );

register_activation_hook( __FILE__, 'ih247_wpim_sync_dropin' );
register_deactivation_hook(
	__FILE__,
	function () {
		ih247_wpim_remove_dropin();
		ih247_wpim_remove_dberror();
	}
);

/* -------------------------------------------------------------------------
 * Admin: settings page (Settings → WP Intermission)
 * ---------------------------------------------------------------------- */

function ih247_wpim_sanitize_html( $html ) {
	// Site owners with unfiltered_html keep full markup (style/script allowed);
	// everyone else is limited to post-safe HTML.
	return current_user_can( 'unfiltered_html' ) ? (string) $html : wp_kses_post( (string) $html );
}

function ih247_wpim_sanitize_countdown( $value ) {
	$value = trim( (string) $value );
	return preg_match( '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/', $value ) ? $value : '';
}

function ih247_wpim_sanitize_cd_end( $value ) {
	return in_array( $value, array( 'none', 'hide', 'golive' ), true ) ? $value : 'none';
}

function ih247_wpim_sanitize_mode( $value ) {
	return in_array( $value, array( 'full', 'template', 'designer' ), true ) ? $value : 'designer';
}

function ih247_wpim_sanitize_status( $value ) {
	return '200' === (string) $value ? '200' : '503';
}

function ih247_wpim_register_settings() {
	$bool = array( 'type' => 'boolean', 'sanitize_callback' => 'rest_sanitize_boolean', 'default' => false );

	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPTION, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_DROPIN, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_CD_ON, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_CD_END, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_cd_end', 'default' => 'none',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_DBERROR, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_FORCE, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_HIDE_CREDIT, $bool );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_MODE, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_mode', 'default' => 'designer',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_STATUS, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_status', 'default' => '503',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_CONTENT, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_html', 'default' => '',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_FULL, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_html', 'default' => '',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_COUNTDOWN, array(
		'type' => 'string', 'sanitize_callback' => 'ih247_wpim_sanitize_countdown', 'default' => '',
	) );
	register_setting( 'ihelp247_wp_intermission', IH247_WPIM_OPT_DESIGNER, array(
		'type' => 'object', 'sanitize_callback' => 'ih247_wpim_sanitize_designer', 'default' => array(),
	) );
}
add_action( 'admin_init', 'ih247_wpim_register_settings' );

function ih247_wpim_menu() {
	add_options_page(
		__( 'iHelp247 WP Intermission', 'wp-intermission' ),
		__( 'WP Intermission', 'wp-intermission' ),
		'manage_options',
		'wp-intermission',
		'ih247_wpim_settings_page'
	);
}
add_action( 'admin_menu', 'ih247_wpim_menu' );

/** WordPress's bundled CodeMirror on the full-HTML textarea. */
function ih247_wpim_admin_assets( $hook ) {
	if ( 'settings_page_wp-intermission' !== $hook ) {
		return;
	}
	wp_enqueue_media(); // Media Library pickers for Designer fields.
	$settings = wp_enqueue_code_editor( array( 'type' => 'text/html' ) );
	if ( false === $settings ) {
		return; // User disabled syntax highlighting — plain textarea still works.
	}
	wp_add_inline_script(
		'code-editor',
		'jQuery(function(){var ta=document.getElementById("ihelp247_wp_intermission_full_html");'
		. 'if(ta){window.ihCM=wp.codeEditor.initialize(ta,' . wp_json_encode( array( 'codemirror' => $settings['codemirror'] ) ) . ');}});'
	);
}
add_action( 'admin_enqueue_scripts', 'ih247_wpim_admin_assets' );

/** One font slot's controls — printed inline with the field it styles. */
function ih247_wpim_font_slot_ui( $slot, $label, $d, $dn, $allow_inherit = false ) {
	?>
	<p style="margin-top:4px;"><em><?php echo esc_html( $label ); ?></em><br />
		<select class="ih-d" name="<?php echo esc_attr( $dn ); ?>[<?php echo esc_attr( $slot ); ?>_source]" onchange="ihFontSlot('<?php echo esc_attr( $slot ); ?>', this.value)">
			<?php if ( $allow_inherit ) : ?>
				<option value="inherit" <?php selected( 'inherit', $d[ $slot . '_source' ] ); ?>><?php esc_html_e( 'Use body font (default)', 'wp-intermission' ); ?></option>
			<?php endif; ?>
			<option value="system" <?php selected( 'system', $d[ $slot . '_source' ] ); ?>><?php esc_html_e( 'System font — native, zero external calls', 'wp-intermission' ); ?></option>
			<option value="google" <?php selected( 'google', $d[ $slot . '_source' ] ); ?>><?php esc_html_e( 'Google Font — easy, but visitors\' browsers call Google (GDPR consideration)', 'wp-intermission' ); ?></option>
			<option value="custom" <?php selected( 'custom', $d[ $slot . '_source' ] ); ?>><?php esc_html_e( 'Self-hosted file — licensed/custom fonts, served from this site only', 'wp-intermission' ); ?></option>
		</select></p>
	<p id="ih-f-<?php echo esc_attr( $slot ); ?>-system" <?php echo 'system' === $d[ $slot . '_source' ] ? '' : 'style="display:none"'; ?>>
		<select class="ih-d" name="<?php echo esc_attr( $dn ); ?>[<?php echo esc_attr( $slot ); ?>_stack]">
			<?php foreach ( ih247_wpim_system_stacks() as $key => $stack ) : ?>
				<option value="<?php echo esc_attr( $key ); ?>" <?php selected( $key, $d[ $slot . '_stack' ] ); ?>><?php echo esc_html( $stack['label'] ); ?></option>
			<?php endforeach; ?>
		</select></p>
	<p id="ih-f-<?php echo esc_attr( $slot ); ?>-google" <?php echo 'google' === $d[ $slot . '_source' ] ? '' : 'style="display:none"'; ?>>
		<span style="position:relative;display:inline-block;">
			<input type="text" autocomplete="off" class="regular-text ih-d ih-gfont" name="<?php echo esc_attr( $dn ); ?>[<?php echo esc_attr( $slot ); ?>_google]" value="<?php echo esc_attr( $d[ $slot . '_google' ] ); ?>" placeholder="<?php esc_attr_e( 'Start typing a Google Font name…', 'wp-intermission' ); ?>" />
			<span class="ih-gf-panel" style="display:none;position:absolute;left:0;top:100%;width:100%;max-height:280px;overflow:auto;background:#fff;border:1px solid #c3c4c7;box-shadow:0 2px 8px rgba(0,0,0,0.15);z-index:99;"></span>
		</span><br />
		<span class="description"><?php esc_html_e( 'Suggestions render in their actual face — click one to apply. The public page loads this font from fonts.googleapis.com (a <link> tag in the page source).', 'wp-intermission' ); ?></span></p>
	<p id="ih-f-<?php echo esc_attr( $slot ); ?>-custom" <?php echo 'custom' === $d[ $slot . '_source' ] ? '' : 'style="display:none"'; ?>>
		<input type="text" class="regular-text ih-d" name="<?php echo esc_attr( $dn ); ?>[<?php echo esc_attr( $slot ); ?>_family]" value="<?php echo esc_attr( $d[ $slot . '_family' ] ); ?>" placeholder="<?php esc_attr_e( 'Font family name', 'wp-intermission' ); ?>" /><br />
		<input type="url" class="regular-text ih-d" id="ih-d-<?php echo esc_attr( $slot ); ?>font" name="<?php echo esc_attr( $dn ); ?>[<?php echo esc_attr( $slot ); ?>_url]" value="<?php echo esc_attr( $d[ $slot . '_url' ] ); ?>" placeholder="<?php esc_attr_e( '.woff2 URL', 'wp-intermission' ); ?>" />
		<button type="button" class="button ih-media" data-target="ih-d-<?php echo esc_attr( $slot ); ?>font"><?php esc_html_e( 'Media Library', 'wp-intermission' ); ?></button><br />
		<span class="description"><?php esc_html_e( 'Upload the .woff2 via Media Library (.woff/.woff2 enabled for admins).', 'wp-intermission' ); ?></span></p>
	<?php
}

function ih247_wpim_settings_page() {
	$enabled   = ih247_wpim_is_enabled();
	$mode      = ih247_wpim_get_mode();
	$status    = (string) ih247_wpim_get_status();
	$dropin_on  = (bool) get_option( IH247_WPIM_OPT_DROPIN, false );
	$foreign    = ! ih247_wpim_dropin_is_ours_or_absent();
	$db_foreign = ! ih247_wpim_dberror_is_ours_or_absent();
	$force      = ih247_wpim_force_overwrite();
	$full_html = (string) get_option( IH247_WPIM_OPT_FULL, '' );
	if ( '' === trim( $full_html ) ) {
		// First visit to full mode: start from the currently-rendered page
		// (tokens intact) so there is a working document to edit, never a blank box.
		$template = ih247_wpim_template_path();
		if ( is_readable( $template ) ) {
			$full_html = str_replace( '{{CONTENT}}', ih247_wpim_get_content(), file_get_contents( $template ) );
		}
	}
	?>
	<div class="wrap">
		<h1><?php esc_html_e( 'iHelp247 WP Intermission', 'wp-intermission' ); ?></h1>

		<form method="post" action="options.php">
			<?php settings_fields( 'ihelp247_wp_intermission' ); ?>
			<table class="form-table" role="presentation">
				<tr>
					<th scope="row"><?php esc_html_e( 'Maintenance mode', 'wp-intermission' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="<?php echo esc_attr( IH247_WPIM_OPTION ); ?>" value="1" <?php checked( $enabled ); ?> />
							<?php esc_html_e( 'Enabled — visitors get the maintenance page. Logged-in editors see the live site.', 'wp-intermission' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Response code', 'wp-intermission' ); ?></th>
					<td>
						<label style="margin-right:18px;">
							<input type="radio" name="<?php echo esc_attr( IH247_WPIM_OPT_STATUS ); ?>" value="503" <?php checked( '503', $status ); ?> />
							<?php esc_html_e( '503 Service Unavailable — short maintenance. Tells search engines it is temporary; nothing gets indexed or de-indexed.', 'wp-intermission' ); ?>
						</label>
						<br />
						<label>
							<input type="radio" name="<?php echo esc_attr( IH247_WPIM_OPT_STATUS ); ?>" value="200" <?php checked( '200', $status ); ?> />
							<?php esc_html_e( '200 OK — extended maintenance / coming-soon. Serves as a normal page; control indexing yourself with a robots meta tag in your HTML.', 'wp-intermission' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Page source', 'wp-intermission' ); ?></th>
					<td>
						<label style="display:block;margin-bottom:6px;">
							<input type="radio" name="<?php echo esc_attr( IH247_WPIM_OPT_MODE ); ?>" value="designer" <?php checked( 'designer', $mode ); ?> onclick="ihMode(this.value)" />
							<?php esc_html_e( 'Designer — simple fields with live preview, no code needed', 'wp-intermission' ); ?>
						</label>
						<label style="display:block;margin-bottom:6px;">
							<input type="radio" name="<?php echo esc_attr( IH247_WPIM_OPT_MODE ); ?>" value="template" <?php checked( 'template', $mode ); ?> onclick="ihMode(this.value)" />
							<?php esc_html_e( 'Styled template + content editor', 'wp-intermission' ); ?>
						</label>
						<label style="display:block;">
							<input type="radio" name="<?php echo esc_attr( IH247_WPIM_OPT_MODE ); ?>" value="full" <?php checked( 'full', $mode ); ?> onclick="ihMode(this.value)" />
							<?php esc_html_e( 'Full custom HTML — you own the entire page: styles, background, everything', 'wp-intermission' ); ?>
						</label>
					</td>
				</tr>
				<tr class="ih-row-designer" <?php echo 'designer' === $mode ? '' : 'style="display:none"'; ?>>
					<th scope="row"><?php esc_html_e( 'Designer', 'wp-intermission' ); ?>
						<p class="description" style="font-weight:normal;margin-top:8px;"><?php esc_html_e( 'Every element isolated. The preview updates live as you edit — save when it looks right.', 'wp-intermission' ); ?></p>
					</th>
					<td>
						<?php $d = ih247_wpim_designer(); $dn = IH247_WPIM_OPT_DESIGNER; ?>
						<div style="display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap;">
						<div style="min-width:340px;max-width:420px;flex:1;">
							<p><label><strong><?php esc_html_e( 'Background image', 'wp-intermission' ); ?></strong><br />
								<input type="url" class="regular-text ih-d" id="ih-d-bg" name="<?php echo esc_attr( $dn ); ?>[bg_url]" value="<?php echo esc_attr( $d['bg_url'] ); ?>" placeholder="<?php esc_attr_e( 'empty = color / dark gradient', 'wp-intermission' ); ?>" /></label>
								<button type="button" class="button ih-media" data-target="ih-d-bg"><?php esc_html_e( 'Media Library', 'wp-intermission' ); ?></button>
								<button type="button" class="button" onclick="ihClear('ih-d-bg')"><?php esc_html_e( 'Remove image', 'wp-intermission' ); ?></button></p>
							<p><strong><?php esc_html_e( 'Background style (under/instead of image)', 'wp-intermission' ); ?></strong><br />
								<select class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_style]" onchange="ihBgStyle(this.value)">
									<option value="default" <?php selected( 'default', $d['bg_style'] ); ?>><?php esc_html_e( 'Stock dark gradient', 'wp-intermission' ); ?></option>
									<option value="solid" <?php selected( 'solid', $d['bg_style'] ); ?>><?php esc_html_e( 'Solid color', 'wp-intermission' ); ?></option>
									<option value="gradient" <?php selected( 'gradient', $d['bg_style'] ); ?>><?php esc_html_e( 'Custom gradient (two colors)', 'wp-intermission' ); ?></option>
								</select>
								<span id="ih-bg-c1" <?php echo 'default' === $d['bg_style'] ? 'style="display:none"' : ''; ?>>
									<input type="color" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_color]" value="<?php echo esc_attr( $d['bg_color'] ? $d['bg_color'] : '#000510' ); ?>" />
								</span>
								<span id="ih-bg-c2" <?php echo 'gradient' === $d['bg_style'] ? '' : 'style="display:none"'; ?>>
									<input type="color" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_color2]" value="<?php echo esc_attr( $d['bg_color2'] ? $d['bg_color2'] : '#0a2540' ); ?>" />
									<select class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_dir]">
										<option value="radial" <?php selected( 'radial', $d['bg_dir'] ); ?>><?php esc_html_e( 'Radial (center glow)', 'wp-intermission' ); ?></option>
										<option value="vertical" <?php selected( 'vertical', $d['bg_dir'] ); ?>><?php esc_html_e( 'Vertical', 'wp-intermission' ); ?></option>
										<option value="diagonal" <?php selected( 'diagonal', $d['bg_dir'] ); ?>><?php esc_html_e( 'Diagonal', 'wp-intermission' ); ?></option>
									</select>
								</span></p>
							<p><label>
								<input type="checkbox" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_overlay]" value="1" <?php checked( '1', $d['bg_overlay'] ); ?> />
								<?php esc_html_e( 'Glass effect — dark overlay + blur layers (recommended over images; turn OFF for light designs)', 'wp-intermission' ); ?>
							</label>
							<br /><span style="display:inline-block;margin-top:6px;"><?php esc_html_e( 'Strength', 'wp-intermission' ); ?></span>
							<input type="range" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[bg_glass_op]" min="10" max="100" step="5" value="<?php echo esc_attr( $d['bg_glass_op'] ); ?>" style="vertical-align:middle;" /></p>
							<hr style="margin:16px 0 12px;border:0;border-top:2px solid #aab0b6;" />
							<p><label><strong><?php esc_html_e( 'Logo', 'wp-intermission' ); ?></strong><br />
								<input type="url" class="regular-text ih-d" id="ih-d-logo" name="<?php echo esc_attr( $dn ); ?>[logo_url]" value="<?php echo esc_attr( $d['logo_url'] ); ?>" placeholder="<?php esc_attr_e( 'empty = no logo', 'wp-intermission' ); ?>" /></label>
								<button type="button" class="button ih-media" data-target="ih-d-logo"><?php esc_html_e( 'Media Library', 'wp-intermission' ); ?></button>
								<button type="button" class="button" onclick="ihClear('ih-d-logo')"><?php esc_html_e( 'Remove image', 'wp-intermission' ); ?></button></p>
							<hr style="margin:16px 0 12px;border:0;border-top:2px solid #aab0b6;" />
							<p><label><strong><?php esc_html_e( 'Title', 'wp-intermission' ); ?></strong><br />
								<input type="text" class="regular-text ih-d" id="ih-d-title" name="<?php echo esc_attr( $dn ); ?>[title]" value="<?php echo esc_attr( $d['title'] ); ?>" /></label>
								<span style="white-space:nowrap;"><button type="button" class="button button-small" onclick="ihWrap('ih-d-title','strong')" title="Bold"><strong>B</strong></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-title','em')" title="Italic"><em>I</em></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-title','u')" title="Underline"><u>U</u></button></span>
								<?php esc_html_e( 'Size', 'wp-intermission' ); ?> <input type="number" class="small-text ih-d" name="<?php echo esc_attr( $dn ); ?>[title_size]" value="<?php echo esc_attr( $d['title_size'] ); ?>" min="8" max="160" />
								<input type="color" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[title_color]" value="<?php echo esc_attr( $d['title_color'] ); ?>" /></p>
							<?php ih247_wpim_font_slot_ui( 'heading', __( 'Title font', 'wp-intermission' ), $d, $dn ); ?>
							<hr style="margin:16px 0 12px;border:0;border-top:2px solid #aab0b6;" />
							<p><label><strong><?php esc_html_e( 'Subtitle', 'wp-intermission' ); ?></strong><br />
								<input type="text" class="regular-text ih-d" id="ih-d-sub" name="<?php echo esc_attr( $dn ); ?>[subtitle]" value="<?php echo esc_attr( $d['subtitle'] ); ?>" placeholder="<?php esc_attr_e( 'empty = hidden', 'wp-intermission' ); ?>" /></label>
								<span style="white-space:nowrap;"><button type="button" class="button button-small" onclick="ihWrap('ih-d-sub','strong')" title="Bold"><strong>B</strong></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-sub','em')" title="Italic"><em>I</em></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-sub','u')" title="Underline"><u>U</u></button></span>
								<?php esc_html_e( 'Size', 'wp-intermission' ); ?> <input type="number" class="small-text ih-d" name="<?php echo esc_attr( $dn ); ?>[subtitle_size]" value="<?php echo esc_attr( $d['subtitle_size'] ); ?>" min="8" max="160" />
								<input type="color" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[subtitle_color]" value="<?php echo esc_attr( $d['subtitle_color'] ); ?>" /></p>
							<hr style="margin:16px 0 12px;border:0;border-top:2px solid #aab0b6;" />
							<p><label><strong><?php esc_html_e( 'Main text', 'wp-intermission' ); ?></strong><br />
								<textarea class="large-text ih-d" rows="3" id="ih-d-text" name="<?php echo esc_attr( $dn ); ?>[text]"><?php echo esc_textarea( $d['text'] ); ?></textarea></label>
								<span style="white-space:nowrap;"><button type="button" class="button button-small" onclick="ihWrap('ih-d-text','strong')" title="Bold"><strong>B</strong></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-text','em')" title="Italic"><em>I</em></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-text','u')" title="Underline"><u>U</u></button></span>
								<span class="description"><?php esc_html_e( 'Select text and click B/I/U, or type HTML — new lines become line breaks automatically.', 'wp-intermission' ); ?></span><br />
								<?php esc_html_e( 'Size', 'wp-intermission' ); ?> <input type="number" class="small-text ih-d" name="<?php echo esc_attr( $dn ); ?>[text_size]" value="<?php echo esc_attr( $d['text_size'] ); ?>" min="8" max="160" />
								<input type="color" class="ih-d" name="<?php echo esc_attr( $dn ); ?>[text_color]" value="<?php echo esc_attr( $d['text_color'] ); ?>" /></p>
							<?php ih247_wpim_font_slot_ui( 'body', __( 'Body font (subtitle, text, footer)', 'wp-intermission' ), $d, $dn ); ?>

							<hr style="margin:16px 0 12px;border:0;border-top:2px solid #aab0b6;" />
							<p><label><strong><?php esc_html_e( 'Disclaimer (footer)', 'wp-intermission' ); ?></strong><br />
								<textarea class="large-text ih-d" rows="3" id="ih-d-disclaimer" name="<?php echo esc_attr( $dn ); ?>[disclaimer]" placeholder="<?php esc_attr_e( 'Legal wording; empty = hidden.', 'wp-intermission' ); ?>"><?php echo esc_textarea( $d['disclaimer'] ); ?></textarea></label>
								<span style="white-space:nowrap;"><button type="button" class="button button-small" onclick="ihWrap('ih-d-disclaimer','strong')" title="Bold"><strong>B</strong></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-disclaimer','em')" title="Italic"><em>I</em></button><button type="button" class="button button-small" onclick="ihWrap('ih-d-disclaimer','u')" title="Underline"><u>U</u></button></span>
								<button type="button" class="button" onclick="ihDisclaimer()"><?php esc_html_e( 'Insert standard no-collection wording', 'wp-intermission' ); ?></button>
								<span class="description"><?php esc_html_e( 'Vetted transparency wording for a page that collects nothing (the GDPR/CCPA-appropriate posture: no data collected means no consent banner required — edit freely, and have counsel review site-specific obligations).', 'wp-intermission' ); ?></span></p>
							<?php ih247_wpim_font_slot_ui( 'footer', __( 'Footer font', 'wp-intermission' ), $d, $dn, true ); ?>
						</div>
						<div id="ih-d-pcol" style="flex:1 1 480px;min-width:360px;max-width:100%;position:sticky;top:46px;align-self:flex-start;">
							<div style="text-align:center;margin-bottom:10px;">
								<strong style="display:block;margin-bottom:6px;"><?php esc_html_e( 'Live preview', 'wp-intermission' ); ?></strong>
								<button type="button" id="ih-vp-desktop" class="button button-primary" onclick="ihViewport('desktop')"><?php esc_html_e( 'Desktop 1920', 'wp-intermission' ); ?></button>
								<button type="button" id="ih-vp-laptop" class="button" onclick="ihViewport('laptop')"><?php esc_html_e( 'Laptop 1440', 'wp-intermission' ); ?></button>
								<button type="button" id="ih-vp-phone" class="button" onclick="ihViewport('phone')"><?php esc_html_e( 'Phone 390', 'wp-intermission' ); ?></button>
							</div>
							<div id="ih-device" style="text-align:center;">
								<div id="ih-frame" style="display:inline-block;background:#0b0e11;box-shadow:0 8px 30px rgba(0,0,0,0.35);">
									<div id="ih-d-pwrap" style="position:relative;overflow:hidden;margin:0 auto;">
										<iframe id="ih-d-preview" style="border:0;background:#000510;display:block;transform-origin:top left;" sandbox="allow-scripts"></iframe>
									</div>
								</div>
								<div id="ih-stand-neck" style="display:none;width:72px;height:44px;background:#181c20;margin:0 auto;"></div>
								<div id="ih-stand-base" style="display:none;height:14px;background:#181c20;border-radius:8px;margin:0 auto;"></div>
							</div>
							<p class="description" style="text-align:center;"><?php esc_html_e( 'True-scale render at real device resolution — proportions, logo size, and line wraps match the finished product. Countdown uses the saved target. Unsaved edits appear instantly; nothing goes live until you Save.', 'wp-intermission' ); ?></p>
						</div>
						</div>
					</td>
				</tr>
				<tr id="ih-row-content" <?php echo 'template' === $mode ? '' : 'style="display:none"'; ?>>
					<th scope="row">
						<?php esc_html_e( 'Page content', 'wp-intermission' ); ?>
						<p class="description" style="font-weight:normal;margin-top:8px;">
							<?php esc_html_e( 'Injected into the styled template. Visual tab to edit, Code tab for raw HTML.', 'wp-intermission' ); ?>
						</p>
					</th>
					<td>
						<?php
						wp_editor(
							ih247_wpim_get_content(),
							'ihelp247_wp_intermission_content_editor',
							array(
								'textarea_name' => IH247_WPIM_OPT_CONTENT,
								'textarea_rows' => 10,
								'media_buttons' => true,
								'wpautop'       => false, // preserve markup exactly as authored
								'quicktags'     => true,  // the "Code" (Text) tab
							)
						);
						?>
					</td>
				</tr>
				<tr id="ih-row-full" <?php echo 'full' === $mode ? '' : 'style="display:none"'; ?>>
					<th scope="row">
						<?php esc_html_e( 'Full page HTML', 'wp-intermission' ); ?>
						<p class="description" style="font-weight:normal;margin-top:8px;">
							<?php esc_html_e( 'The complete document, served exactly as written — the plugin never rewrites what you store here, so hardcoded URLs stay hardcoded. Upload images via Media Library and use their URLs, or use {{ASSETS_URL}} — it resolves to wp-content/uploads/wp-intermission/ (update-proof, same relative path on every site, so shared fleet HTML is portable).', 'wp-intermission' ); ?>
						</p>
					</th>
					<td>
						<textarea id="ihelp247_wp_intermission_full_html" name="<?php echo esc_attr( IH247_WPIM_OPT_FULL ); ?>" rows="22" style="width:100%;font-family:monospace;"><?php echo esc_textarea( $full_html ); ?></textarea>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Tokens', 'wp-intermission' ); ?></th>
					<td>
						<p class="description">
							<?php
							printf(
								/* translators: 1: countdown token, 2,3,4: placeholder names */
								esc_html__( 'Work in both modes: %1$s inserts the countdown timer; %2$s, %3$s, and %4$s are also replaced.', 'wp-intermission' ),
								'<code>' . esc_html( IH247_WPIM_COUNTDOWN_TOKEN ) . '</code>',
								'<code>{{SITE_NAME}}</code>',
								'<code>{{YEAR}}</code>',
								'<code>{{ASSETS_URL}}</code>'
							);
							?>
						</p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Countdown', 'wp-intermission' ); ?></th>
					<td>
						<?php $cd_on = ih247_wpim_cd_enabled(); $cd_end_v = ih247_wpim_cd_end(); ?>
						<p style="margin-top:0;">
							<label>
								<input type="checkbox" id="ih-cd-on" name="<?php echo esc_attr( IH247_WPIM_OPT_CD_ON ); ?>" value="1" <?php checked( $cd_on ); ?> onchange="ihCdUI()" />
								<strong><?php esc_html_e( 'Enable countdown', 'wp-intermission' ); ?></strong>
							</label>
							&nbsp; <?php esc_html_e( 'At zero:', 'wp-intermission' ); ?>
							<select id="ih-cd-end" name="<?php echo esc_attr( IH247_WPIM_OPT_CD_END ); ?>" onchange="ihCdUI()" <?php disabled( ! $cd_on ); ?>>
								<option value="none" <?php selected( 'none', $cd_end_v ); ?>><?php esc_html_e( 'Keep showing 00s (display only)', 'wp-intermission' ); ?></option>
								<option value="hide" <?php selected( 'hide', $cd_end_v ); ?>><?php esc_html_e( 'Hide the countdown', 'wp-intermission' ); ?></option>
								<option value="golive" <?php selected( 'golive', $cd_end_v ); ?>><?php esc_html_e( 'Take the site live (maintenance off at T-0)', 'wp-intermission' ); ?></option>
							</select>
						</p>
						<p>
							<?php esc_html_e( 'Target:', 'wp-intermission' ); ?>
							<input type="datetime-local" id="ih-cd-date"
								name="<?php echo esc_attr( IH247_WPIM_OPT_COUNTDOWN ); ?>"
								value="<?php echo esc_attr( get_option( IH247_WPIM_OPT_COUNTDOWN, '' ) ); ?>" onchange="ihCdUI()" oninput="ihCdUI()" />
							<span class="description"><?php echo esc_html( sprintf( /* translators: %s: timezone */ __( 'Site timezone (%s). The date is kept when the countdown is disabled — unticking hides the timer without losing the date.', 'wp-intermission' ), wp_timezone_string() ) ); ?></span>
						</p>
						<p id="ih-cd-warn" style="display:none;font-weight:600;"></p>
						<?php $d_cd = ih247_wpim_designer(); $dn_cd = IH247_WPIM_OPT_DESIGNER; ?>
						<p style="margin-top:10px;">
							<?php esc_html_e( 'Style:', 'wp-intermission' ); ?>
							<select class="ih-d" name="<?php echo esc_attr( $dn_cd ); ?>[cd_shape]">
								<option value="square" <?php selected( 'square', $d_cd['cd_shape'] ); ?>><?php esc_html_e( 'Squares', 'wp-intermission' ); ?></option>
								<option value="rounded" <?php selected( 'rounded', $d_cd['cd_shape'] ); ?>><?php esc_html_e( 'Rounded corners', 'wp-intermission' ); ?></option>
								<option value="circle" <?php selected( 'circle', $d_cd['cd_shape'] ); ?>><?php esc_html_e( 'Circles', 'wp-intermission' ); ?></option>
							</select>
							<input type="color" class="ih-d" name="<?php echo esc_attr( $dn_cd ); ?>[cd_color]" value="<?php echo esc_attr( $d_cd['cd_color'] ? $d_cd['cd_color'] : '#ffffff' ); ?>" />
							<span class="description"><?php esc_html_e( 'Digit color — labels, borders, and fill tint derive from it (pick a dark color on light backgrounds). Applies in every page-source mode.', 'wp-intermission' ); ?></span>
						</p>
						<?php ih247_wpim_font_slot_ui( 'cd', __( 'Countdown font — digital faces like Orbitron, VT323, or Share Tech Mono shine here; the monospace system stack gives rock-steady digits', 'wp-intermission' ), $d_cd, $dn_cd, true ); ?>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Core-update coverage', 'wp-intermission' ); ?></th>
					<td>
						<label>
							<input type="checkbox" id="ih-dropin" name="<?php echo esc_attr( IH247_WPIM_OPT_DROPIN ); ?>" value="1" <?php checked( $dropin_on ); ?> <?php disabled( $foreign && ! $force ); ?> />
							<?php esc_html_e( 'Serve this same page while WordPress itself is updating (plugins cannot run then). Generates wp-content/maintenance.php, keeps it in sync with every save, removes it on deactivation. Always sends 503 — update windows are temporary by nature.', 'wp-intermission' ); ?>
						</label>
						<?php if ( $foreign && ! $force ) : ?>
							<p class="description" style="color:#d63638;">
								<?php esc_html_e( 'A wp-content/maintenance.php file already exists and was not created by iHelp247 WP Intermission. For safety, iHelp247 WP Intermission will not overwrite files owned by other plugins or hosting tools (some keep this file in place permanently and only toggle the hidden .maintenance flag, so its presence does not mean their maintenance is on). Disable the other maintenance tool, delete wp-content/maintenance.php, and save your settings again — or tick Force overwrite below, with its caveats.', 'wp-intermission' ); ?>
							</p>
						<?php elseif ( $foreign && $force ) : ?>
							<p class="description" style="color:#996800;">
								<?php esc_html_e( 'Force overwrite is on: the foreign wp-content/maintenance.php will be replaced with your designed page the next time you save.', 'wp-intermission' ); ?>
							</p>
						<?php endif; ?>
						<p style="margin:10px 0 0;">
							<label>
								<input type="checkbox" id="ih-force" name="<?php echo esc_attr( IH247_WPIM_OPT_FORCE ); ?>" value="1" <?php checked( $force ); ?> onchange="ihForce(this)" />
								<strong><?php esc_html_e( 'Force overwrite', 'wp-intermission' ); ?></strong> —
								<?php esc_html_e( 'overwrite a foreign wp-content/maintenance.php (and db-error.php below) when saving. What gets written is a snapshot of your designed page above — never a generic screen — and ticking this enables core-update coverage automatically. Unreliable by design: the file is only checked and replaced when you save these settings — it is not monitored, and whatever tool created it can put its own copy back at any time. The clean fix is still one owner per site.', 'wp-intermission' ); ?>
							</label>
						</p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Database-failure coverage', 'wp-intermission' ); ?></th>
					<td>
						<label>
							<input type="checkbox" id="ih-db" name="<?php echo esc_attr( IH247_WPIM_OPT_DBERROR ); ?>" value="1" <?php checked( (bool) get_option( IH247_WPIM_OPT_DBERROR, false ) ); ?> <?php disabled( $db_foreign && ! $force ); ?> />
							<?php esc_html_e( 'Serve this same page when WordPress cannot reach the database, instead of the bare "Error establishing a database connection" screen. Generates wp-content/db-error.php (503, Retry-After 300), kept in sync with every save, removed on deactivation. A timestamped HTML comment marks it as a DB outage in view-source. Leave OFF in dev/diagnostic environments where you want raw errors visible.', 'wp-intermission' ); ?>
						</label>
						<?php if ( $db_foreign && ! $force ) : ?>
							<p class="description" style="color:#d63638;">
								<?php esc_html_e( 'A wp-content/db-error.php file already exists and was not created by iHelp247 WP Intermission. For safety it will not be overwritten — remove the other tool\'s file and save again, or tick Force overwrite in the Core-update coverage section above.', 'wp-intermission' ); ?>
							</p>
						<?php elseif ( $db_foreign && $force ) : ?>
							<p class="description" style="color:#996800;">
								<?php esc_html_e( 'Force overwrite is on: the foreign wp-content/db-error.php will be replaced with your designed page the next time you save.', 'wp-intermission' ); ?>
							</p>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Preview', 'wp-intermission' ); ?></th>
					<td>
						<a href="<?php echo esc_url( home_url( '/?ihelp247_wp_intermission_preview=1' ) ); ?>" target="_blank">
							<?php esc_html_e( 'Preview the maintenance page', 'wp-intermission' ); ?>
						</a>
						<p class="description"><?php esc_html_e( 'Save first, then preview. Works while logged in, whether or not maintenance mode is enabled.', 'wp-intermission' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Help', 'wp-intermission' ); ?></th>
					<td>
						<a href="<?php echo esc_url( apply_filters( 'ihelp247_wp_intermission_docs_url', IH247_WPIM_DOCS_URL ) ); ?>" target="_blank">
							<?php esc_html_e( 'User guide & troubleshooting', 'wp-intermission' ); ?>
						</a>
						<p class="description"><?php esc_html_e( 'Plain-language guide with a self-diagnosis section. A copy also ships in the plugin\'s docs/ folder, so it works offline.', 'wp-intermission' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<img src="<?php echo esc_url( plugins_url( 'assets/logo-dark.svg', __FILE__ ) ); ?>" alt="<?php esc_attr_e( 'iHelp247 — Superior Technology Ecosystems', 'wp-intermission' ); ?>" width="152" style="max-width:100%;height:auto;" />
					</th>
					<td>
						<p style="margin-top:0;"><?php esc_html_e( 'If WP Intermission is earning its keep in your world, letting us know is what keeps us building — a quick review, or an energy drink. Any amount, one-time or monthly, goes straight to feeding the developers\' break room. No pressure; we\'re glad it\'s useful either way.', 'wp-intermission' ); ?></p>
						<p>
							<a class="button" href="<?php echo esc_url( IH247_WPIM_DONATE_URL ); ?>" target="_blank" rel="noopener"><?php esc_html_e( '☕ Keep the energy drinks & coffee flowing', 'wp-intermission' ); ?></a>
							<a class="button" href="<?php echo esc_url( IH247_WPIM_REVIEW_URL ); ?>" target="_blank" rel="noopener"><?php esc_html_e( '★ Leave a review', 'wp-intermission' ); ?></a>
							<a class="button" href="<?php echo esc_url( IH247_WPIM_SUPPORT_URL ); ?>" target="_blank" rel="noopener"><?php esc_html_e( 'Support', 'wp-intermission' ); ?></a>
						</p>
						<p class="description">
							<a href="<?php echo esc_url( IH247_WPIM_PROJECTS_URL ); ?>" target="_blank" rel="noopener"><?php esc_html_e( 'More free tools from iHelp247 →', 'wp-intermission' ); ?></a>
						</p>
						<p style="margin-bottom:0;">
							<label>
								<input type="checkbox" name="<?php echo esc_attr( IH247_WPIM_OPT_HIDE_CREDIT ); ?>" value="1" <?php checked( (bool) get_option( IH247_WPIM_OPT_HIDE_CREDIT, false ) ); ?> />
								<?php esc_html_e( 'Hide the small "intermission by iHelp247" link in the corner of the maintenance page. Free either way — the link just helps others find the plugin.', 'wp-intermission' ); ?>
							</label>
						</p>
					</td>
				</tr>
			</table>
			<?php submit_button(); ?>
		</form>

		<script>
		/* Google Fonts picker — bundled list of popular families (no API key,
		   no external call for the list itself). Suggestions load their real
		   faces via one css2 stylesheet and render in-face for confirmation.
		   Free-typing any family not in this list still works. */
		var IH_GF = ["Roboto","Open Sans","Lato","Montserrat","Oswald","Raleway","Poppins","Inter","Nunito","Nunito Sans","Merriweather","Merriweather Sans","Playfair Display","Source Sans 3","Source Serif 4","Source Code Pro","Ubuntu","PT Sans","PT Serif","Noto Sans","Noto Serif","Rubik","Work Sans","Fira Sans","Fira Code","Quicksand","Karla","Mulish","Barlow","Barlow Condensed","Manrope","Josefin Sans","Inconsolata","DM Sans","DM Serif Display","Space Grotesk","Space Mono","Bebas Neue","Anton","Archivo","Archivo Black","Cabin","Catamaran","Chivo","Cormorant","Cormorant Garamond","Crimson Text","Dancing Script","Pacifico","Caveat","Satisfy","Great Vibes","Lobster","Abril Fatface","Alegreya","Alegreya Sans","Amatic SC","Asap","Assistant","Bitter","Bree Serif","Cardo","Comfortaa","Concert One","Domine","Dosis","EB Garamond","Exo 2","Fjalla One","Frank Ruhl Libre","Heebo","Hind","IBM Plex Sans","IBM Plex Serif","IBM Plex Mono","Indie Flower","Jost","Kanit","Lexend","Libre Baskerville","Libre Franklin","Lora","Maven Pro","Mukta","Overpass","Oxygen","Permanent Marker","Prompt","Public Sans","Questrial","Righteous","Roboto Condensed","Roboto Mono","Roboto Slab","Rokkitt","Sarabun","Shadows Into Light","Signika","Sora","Spectral","Teko","Titillium Web","Varela Round","Vollkorn","Yanone Kaffeesatz","Zilla Slab","Outfit","Plus Jakarta Sans","Figtree","Onest","Geologica","Schibsted Grotesk","Instrument Sans","Instrument Serif","Bricolage Grotesque","Gabarito","Playwrite NZ","Playwrite NZ Guides","Playwrite US Modern","Playwrite US Trad","Playwrite AU SA","Playwrite DE Grund","Michroma","Orbitron","Rajdhani","Russo One","Audiowide","Exo","Chakra Petch","Saira","Syne","Unbounded","Tektur","VT323","Share Tech Mono","Press Start 2P"];
		document.querySelectorAll('.ih-gfont').forEach(function(inp){
			var panel = inp.parentNode.querySelector('.ih-gf-panel');
			var squelch = false;
			var render = function(){
				if (squelch) { squelch = false; panel.style.display = 'none'; return; }
				var q = inp.value.trim().toLowerCase();
				if (q.length < 2) { panel.style.display = 'none'; return; }
				var hits = IH_GF.filter(function(f){ return f.toLowerCase().indexOf(q) !== -1; }).slice(0, 8);
				if (!hits.length) { panel.style.display = 'none'; return; }
				var link = document.getElementById('ih-gf-sugg');
				if (!link) { link = document.createElement('link'); link.id = 'ih-gf-sugg'; link.rel = 'stylesheet'; document.head.appendChild(link); }
				link.href = 'https://fonts.googleapis.com/css2?' + hits.map(function(f){ return 'family=' + f.replace(/ /g, '+'); }).join('&') + '&display=swap';
				panel.innerHTML = '';
				hits.forEach(function(f){
					var item = document.createElement('span');
					item.textContent = f;
					item.style.cssText = "display:block;padding:7px 10px;cursor:pointer;font-size:16px;color:#1d2327;border-bottom:1px solid #f0f0f1;font-family:'" + f + "', sans-serif;";
					item.onmousedown = function(e){
						e.preventDefault();
						inp.value = f;
						squelch = true; // the input event below re-triggers render; swallow it
						panel.style.display = 'none';
						inp.dispatchEvent(new Event('input', { bubbles: true }));
					};
					panel.appendChild(item);
				});
				panel.style.display = 'block';
			};
			inp.addEventListener('input', render);
			inp.addEventListener('focus', render);
			inp.addEventListener('blur', function(){ setTimeout(function(){ panel.style.display = 'none'; }, 150); });
		});

		/* Countdown UI state: end-select disabled until enabled; warnings for
		   enabled-without-date and go-live-with-past-date. */
		function ihCdUI(){
			var on   = document.getElementById('ih-cd-on').checked;
			var date = document.getElementById('ih-cd-date').value;
			var end  = document.getElementById('ih-cd-end');
			var warn = document.getElementById('ih-cd-warn');
			end.disabled = !on;
			var msg = '', color = '';
			if (on && !date) {
				msg = '<?php echo esc_js( __( 'Countdown is enabled but no date is set — nothing will display until you pick one.', 'wp-intermission' ) ); ?>';
				color = '#996800';
			} else if (on && end.value === 'golive' && date && (new Date(date)).getTime() <= Date.now()) {
				msg = '<?php echo esc_js( __( 'Warning: the target is in the past — saving now takes the site live immediately (maintenance mode turns off).', 'wp-intermission' ) ); ?>';
				color = '#d63638';
			}
			warn.textContent = msg;
			warn.style.color = color;
			warn.style.display = msg ? 'block' : 'none';
			if (typeof ihPreview === 'function') { ihPreview(); }
		}
		/* Force overwrite implies core-update coverage: ticking it unlocks and
		   auto-enables the coverage checkboxes (a disabled checkbox would not
		   submit, so the unlock matters). A server-side backstop mirrors this. */
		function ihForce(cb){
			if (!cb.checked) { return; }
			var d = document.getElementById('ih-dropin');
			if (d) { d.disabled = false; d.checked = true; }
			var b = document.getElementById('ih-db');
			if (b) { b.disabled = false; }
		}
		/* B/I/U as a TOGGLE: no selection styles the whole field (tokens included);
		   clicking again on already-styled content unwraps it instead of stacking. */
		function ihWrap(id, tag){
			var el = document.getElementById(id);
			var s = el.selectionStart, e = el.selectionEnd, v = el.value;
			if (s === e) { s = 0; e = v.length; } // nothing selected: whole field
			var sel = v.substring(s, e);
			var open = '<' + tag + '>', close = '</' + tag + '>';
			var t = sel.trim();
			if (t.length >= open.length + close.length && t.indexOf(open) === 0 && t.lastIndexOf(close) === t.length - close.length) {
				var inner = t.substring(open.length, t.length - close.length);
				el.value = v.substring(0, s) + inner + v.substring(e);
				e = s + inner.length;
			} else {
				if (!sel) { sel = 'text'; }
				el.value = v.substring(0, s) + open + sel + close + v.substring(e);
				e = s + open.length + sel.length + close.length;
			}
			el.focus();
			el.selectionStart = s; el.selectionEnd = e;
			el.dispatchEvent(new Event('input', { bubbles: true }));
		}
		function ihClear(id){
			var el = document.getElementById(id);
			el.value = '';
			el.dispatchEvent(new Event('input', { bubbles: true }));
		}
		function ihBgStyle(v){
			document.getElementById('ih-bg-c1').style.display = (v === 'default') ? 'none' : '';
			document.getElementById('ih-bg-c2').style.display = (v === 'gradient') ? '' : 'none';
		}
		/* True-scale preview inside CSS device chrome: the page is laid out at
		   real device pixels, scaled to fit, and the frame hugs it exactly —
		   no dead space, no skew. Monitor gets a stand, laptop a deck, phone
		   a rounded bezel. */
		var ihVP = 'desktop';
		var IH_VPS = { desktop: [1920, 1080], laptop: [1440, 900], phone: [390, 844] };
		function ihViewport(v){
			ihVP = v;
			var dims = IH_VPS[v];
			var col   = document.getElementById('ih-d-pcol');
			var frame = document.getElementById('ih-frame');
			var wrap  = document.getElementById('ih-d-pwrap');
			var f     = document.getElementById('ih-d-preview');
			var neck  = document.getElementById('ih-stand-neck');
			var base  = document.getElementById('ih-stand-base');

			var pad   = (v === 'phone') ? 12 : 14;
			var avail = Math.max(240, col.clientWidth - 2 * pad - 8);
			if (v === 'phone') { avail = Math.min(avail, 300); }
			var scale = Math.min(1, avail / dims[0]);
			var w = Math.round(dims[0] * scale), h = Math.round(dims[1] * scale);

			f.style.width  = dims[0] + 'px';
			f.style.height = dims[1] + 'px';
			f.style.transform = 'scale(' + scale + ')';
			wrap.style.width  = w + 'px';
			wrap.style.height = h + 'px';

			if (v === 'phone') {
				frame.style.padding = '16px 12px';
				frame.style.borderRadius = '36px';
				wrap.style.borderRadius = '22px';
				neck.style.display = 'none';
				base.style.display = 'none';
			} else if (v === 'laptop') {
				frame.style.padding = pad + 'px';
				frame.style.borderRadius = '14px 14px 0 0';
				wrap.style.borderRadius = '4px';
				neck.style.display = 'none';
				base.style.display = 'block';
				base.style.width = (w + 2 * pad + 84) + 'px';
				base.style.height = '16px';
				base.style.borderRadius = '0 0 14px 14px';
			} else {
				frame.style.padding = pad + 'px';
				frame.style.borderRadius = '10px';
				wrap.style.borderRadius = '3px';
				neck.style.display = 'block';
				base.style.display = 'block';
				base.style.width = Math.max(180, Math.round(w * 0.28)) + 'px';
				base.style.height = '14px';
				base.style.borderRadius = '8px';
			}

			['desktop','laptop','phone'].forEach(function(k){
				document.getElementById('ih-vp-' + k).classList.toggle('button-primary', k === v);
			});
		}
		window.addEventListener('resize', function(){ ihViewport(ihVP); });
		function ihFontSlot(slot, v){
			['system','google','custom'].forEach(function(s){
				var el = document.getElementById('ih-f-' + slot + '-' + s);
				if (el) { el.style.display = (v === s) ? '' : 'none'; }
			});
		}
		function ihDisclaimer(){
			var ta = document.getElementById('ih-d-disclaimer');
			ta.value = <?php echo wp_json_encode( __( 'This page does not collect, store, or process any personal data. No cookies are set, no analytics or tracking technologies run, and no information is transmitted to third parties. This site is temporarily unavailable while we perform maintenance; normal service and our full privacy policy resume when the site returns. © {{YEAR}} {{SITE_NAME}}. All rights reserved.', 'wp-intermission' ) ); ?>;
			ta.dispatchEvent(new Event('input', { bubbles: true }));
		}
		function ihMode(m){
			document.getElementById('ih-row-content').style.display = (m === 'template') ? '' : 'none';
			document.getElementById('ih-row-full').style.display = (m === 'full') ? '' : 'none';
			document.querySelectorAll('.ih-row-designer').forEach(function(r){ r.style.display = (m === 'designer') ? '' : 'none'; });
			if (m === 'full' && window.ihCM && window.ihCM.codemirror) { window.ihCM.codemirror.refresh(); }
			if (m === 'designer') { ihPreview(); setTimeout(function(){ ihViewport(ihVP); }, 50); }
		}

		/* Media Library pickers */
		document.querySelectorAll('.ih-media').forEach(function(btn){
			btn.addEventListener('click', function(){
				var target = document.getElementById(btn.getAttribute('data-target'));
				var frame = wp.media({ title: '<?php echo esc_js( __( 'Select or upload', 'wp-intermission' ) ); ?>', multiple: false });
				frame.on('select', function(){
					target.value = frame.state().get('selection').first().toJSON().url;
					target.dispatchEvent(new Event('input', { bubbles: true }));
				});
				frame.open();
			});
		});

		/* Live preview — debounced re-render of unsaved Designer fields */
		var ihPT = null;
		function ihPreview(){
			clearTimeout(ihPT);
			ihPT = setTimeout(function(){
				var data = new FormData();
				data.append('action', 'ih247_wpim_designer_preview');
				data.append('nonce', '<?php echo esc_js( wp_create_nonce( 'ih247_wpim_preview' ) ); ?>');
				document.querySelectorAll('.ih-d').forEach(function(el){
					var m = el.name.match(/\[(\w+)\]/);
					if (m) { data.append('d[' + m[1] + ']', (el.type === 'checkbox') ? (el.checked ? '1' : '') : el.value); }
				});
				data.append('cd_on', document.getElementById('ih-cd-on').checked ? '1' : '');
				data.append('cd_target', document.getElementById('ih-cd-date').value);
				data.append('cd_end', document.getElementById('ih-cd-end').value);
				fetch(ajaxurl, { method: 'POST', body: data, credentials: 'same-origin' })
					.then(function(r){ return r.text(); })
					.then(function(html){ document.getElementById('ih-d-preview').srcdoc = html; });
			}, 350);
		}
		document.querySelectorAll('.ih-d').forEach(function(el){
			el.addEventListener('input', ihPreview);
			el.addEventListener('change', ihPreview);
		});
		ihCdUI();
		<?php if ( 'designer' === $mode ) : ?>ihViewport('desktop');<?php endif; ?>
		</script>
	</div>
	<?php
}

/* -------------------------------------------------------------------------
 * GitHub release updates — WordPress's native mechanism for third-party
 * update sources. Because our "Update URI" header points at github.com,
 * core fires the `update_plugins_github.com` hook during its normal update
 * checks; we answer it from the repo's latest Release. Sites then update
 * through the standard Plugins screen like any other plugin.
 *
 * NOTE for wordpress.org directory hosting: the directory serves updates
 * itself and disallows third-party update sources — if this plugin is ever
 * submitted there, remove this block and the Update URI header.
 * ---------------------------------------------------------------------- */

function ih247_wpim_github_update( $update, $plugin_data, $plugin_file, $locales ) {
	if ( plugin_basename( __FILE__ ) !== $plugin_file ) {
		return $update;
	}

	$info = get_transient( 'ih247_wpim_gh_release' );
	if ( false === $info ) {
		$info = array( 'version' => '', 'zip' => '' );
		$resp = wp_remote_get(
			'https://api.github.com/repos/iHelp247/wp-intermission/releases/latest',
			array(
				'timeout' => 5,
				'headers' => array(
					'Accept'     => 'application/vnd.github+json',
					'User-Agent' => 'wp-intermission/' . IH247_WPIM_VERSION,
				),
			)
		);
		if ( ! is_wp_error( $resp ) && 200 === wp_remote_retrieve_response_code( $resp ) ) {
			$body = json_decode( wp_remote_retrieve_body( $resp ), true );
			$tag  = isset( $body['tag_name'] ) ? ltrim( (string) $body['tag_name'], 'v' ) : '';
			$zip  = '';
			// Only a release ASSET zip is usable — GitHub's auto zipball wraps
			// the code in a "iHelp247-wp-intermission-<hash>" folder, which would
			// break the plugin slug on install.
			foreach ( isset( $body['assets'] ) ? (array) $body['assets'] : array() as $asset ) {
				if ( isset( $asset['name'], $asset['browser_download_url'] ) && '.zip' === substr( $asset['name'], -4 ) ) {
					$zip = $asset['browser_download_url'];
					break;
				}
			}
			$info = array( 'version' => $tag, 'zip' => $zip );
		}
		set_transient( 'ih247_wpim_gh_release', $info, 12 * HOUR_IN_SECONDS ); // fail-soft: cache misses too
	}

	if ( $info['version'] && $info['zip'] && version_compare( $info['version'], IH247_WPIM_VERSION, '>' ) ) {
		return array(
			'id'      => 'https://github.com/iHelp247/wp-intermission',
			'slug'    => 'wp-intermission',
			'plugin'  => $plugin_file,
			'version' => $info['version'],
			'url'     => 'https://github.com/iHelp247/wp-intermission',
			'package' => $info['zip'],
		);
	}
	return $update;
}
add_filter( 'update_plugins_github.com', 'ih247_wpim_github_update', 10, 4 );

/* Quick link on the Plugins screen. */
function ih247_wpim_action_links( $links ) {
	array_unshift(
		$links,
		'<a href="' . esc_url( admin_url( 'options-general.php?page=wp-intermission' ) ) . '">' . esc_html__( 'Settings', 'wp-intermission' ) . '</a>'
	);
	return $links;
}
add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'ih247_wpim_action_links' );

/* Unmissable admin-bar badge while maintenance mode is on — with a live
 * countdown beside it when a future target is set. */
function ih247_wpim_admin_bar( $bar ) {
	if ( ! ih247_wpim_is_enabled() || ! current_user_can( 'manage_options' ) ) {
		return;
	}
	$title = '<span style="background:#d63638;color:#fff;padding:0 8px;border-radius:2px;">' . esc_html__( 'MAINTENANCE ON', 'wp-intermission' ) . '</span>';

	$ts = ih247_wpim_countdown_ts();
	if ( $ts && $ts > time() ) {
		$title .= ' <span id="ih-abar-cd" data-t="' . esc_attr( $ts * 1000 ) . '"'
			. ' style="background:#1d2327;color:#fff;padding:0 8px;border-radius:2px;font-variant-numeric:tabular-nums;">…</span>';
	}

	$bar->add_node(
		array(
			'id'    => 'wp-intermission',
			'title' => $title,
			'href'  => admin_url( 'options-general.php?page=wp-intermission' ),
		)
	);
}
add_action( 'admin_bar_menu', 'ih247_wpim_admin_bar', 100 );

/** Tick the admin-bar countdown (front-end and wp-admin alike). */
function ih247_wpim_admin_bar_script() {
	if ( ! is_admin_bar_showing() ) {
		return;
	}
	echo '<script>(function(){var el=document.getElementById("ih-abar-cd");if(!el)return;'
		. 'var t=+el.getAttribute("data-t"),p=function(n){return("0"+n).slice(-2)};'
		. 'var f=function(){var d=t-Date.now();if(d<0)d=0;var s=Math.floor(d/1000);'
		. 'el.textContent=Math.floor(s/86400)+"d "+p(Math.floor((s%86400)/3600))+":"+p(Math.floor((s%3600)/60))+":"+p(s%60);};'
		. 'f();setInterval(f,1000);})();</script>';
}
add_action( 'admin_footer', 'ih247_wpim_admin_bar_script' );
add_action( 'wp_footer', 'ih247_wpim_admin_bar_script' );
